server:
  port: 7001

spring:
  application:
    name: microservice-consumer-feign

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka1.com:9001/eureka/,http://eureka2.com:9002/eureka/,http://eureka3.com:9003/eureka/
  instance:
    instance-id: microservicecloud-consumer-feign
    prefer-ip-address: true