server:
  port: 8005

mybatis:
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations:
    - "classpath:mapping/*.xml"                     # mapper映射文件
  type-aliases-package: com.pdg.common.entity            # 别名类所在包

spring:
  application:
    name: microservice-provider                          #微服务的名字
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver               # oracle驱动包
#    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    url: jdbc:oracle:thin:@localhost:1521:ocle                    # 数据库名称
    username: scott
    password: 123456
    dbcp2:
      initial-size: 5                                         # 初始化连接数
      max-total: 5                                            # 最大连接数
      max-wait-millis: 200                                    # 等待连接获取的最大超时时间
      min-idle: 5

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka1.com:9001/eureka/,http://eureka2.com:9002/eureka/,http://eureka3.com:9003/eureka/
  instance:
    instance-id: microservicecloud-provider-hystrix
    prefer-ip-address: true

info:
  app.name: microservicecloud-provider
  company.name: com.pdg
  build.artifactId: $project.artifactId
  build.version: $project.version
